# Generated by Django 5.0.6 on 2024-08-22 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('REGISTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
                ('SERVICES', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.services')),
            ],
        ),
    ]
